language: node_js
node_js:
    - '8'

cache:
    yarn: true
    directories:
        - node_modules
        - dist/

env:
    global:
        - GITHUB_ORG="https://GH_TOKEN@github.com"
        - REPO_NAME="ng-simple-cssgrid-generator"
        - GITHUB_NAME="railsstudent"
        - GITHUB_EMAIL="cleung334@gmail.com"

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
    - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
    - yarn install --pure-lockfile

script:
    - yarn audit
    - yarn lint
    - yarn test-headless
    - yarn build-ngh
    - ngh --repo="$GITHUB_ORG/$GITHUB_NAME/$REPO_NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --dir=dist/ng-simple-cssgrid-generator --no-silent

branches:
    only:
        - master
