language: node_js
node_js:
    - '12'

cache:
    npm: true
    directories:
        - node_modules
        - dist/

env:
    global:
        - GITHUB_ORG="https://GH_TOKEN@github.com"
        - REPO_NAME="ng-simple-cssgrid-generator"
        - GITHUB_NAME="railsstudent"
        - GITHUB_EMAIL="cleung334@gmail.com"
        - BASE_HREF="https://railsstudent.github.io"

before_script:
    - npm install

script:
    - npm audit --audit-level=moderate
    - npm run lint
    - npm run test-headless

after_success:
    - ng deploy --base-href="$BASE_HREF/$REPO_NAME/" --repo="$GITHUB_ORG/$GITHUB_NAME/$REPO_NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --no-silent

branches:
    only:
        - master
